import type { SpiderDirective } from "../directives/spider.js";

/**
 * Generates a scrapy settings.py for a project containing multiple spiders.
 */
export function generateSettings(
  projectName: string,
  spiders: SpiderDirective[],
): string {
  const domains = [...new Set(spiders.flatMap((s) => s.allowedDomains))];

  return `"""Scrapy settings for ${projectName}.

Generated by @jadecli/scrapy-cli.
Spiders: ${spiders.map((s) => s.name).join(", ")}
Domains: ${domains.join(", ")}
"""

BOT_NAME = "${projectName}"
SPIDER_MODULES = ["${projectName}.spiders"]
NEWSPIDER_MODULE = "${projectName}.spiders"

ROBOTSTXT_OBEY = True
CONCURRENT_REQUESTS = 8
DOWNLOAD_DELAY = 1.0
COOKIES_ENABLED = False

USER_AGENT = "jadecli-${projectName}/0.1 (+https://github.com/jadecli/platform-manager)"

LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s [%(name)s] %(levelname)s: %(message)s"

REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
FEED_EXPORT_ENCODING = "utf-8"

# AutoThrottle
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
AUTOTHROTTLE_TARGET_CONCURRENCY = 2.0
AUTOTHROTTLE_MAX_DELAY = 30

# Retry
RETRY_ENABLED = True
RETRY_TIMES = 3
RETRY_HTTP_CODES = [500, 502, 503, 504, 522, 524, 408, 429]
`;
}
