import type { SpiderDirective } from "../directives/spider.js";
import type { FieldDef } from "../primitives/selector.js";
import { PRESETS } from "../primitives/rate-limit.js";

const BASE_CLASSES: Record<string, string> = {
  crawl: "CrawlSpider",
  sitemap: "SitemapSpider",
  feed: "XMLFeedSpider",
  api: "Spider",
  local: "Spider",
};

function toPythonClassName(name: string): string {
  return name
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("")
    + "Spider";
}

function indent(lines: string[], level = 1): string {
  const prefix = "    ".repeat(level);
  return lines.map((l) => (l.trim() ? prefix + l : "")).join("\n");
}

function genSelectorCode(field: FieldDef): string {
  const { selector } = field;
  const method = selector.type === "css" ? "css" : "xpath";
  let code = `response.${method}("${selector.query}")`;

  if (selector.attr) {
    code += `.attrib["${selector.attr}"]` ;
  } else if (selector.re) {
    code += `.re_first(r"${selector.re}")`;
  } else if (selector.extract === "all") {
    code += ".getall()";
  } else {
    code += ".get()";
  }

  if (selector.default !== undefined) {
    code = `(${code} or "${selector.default}")`;
  }

  if (field.type === "int") code = `int(${code}) if ${code.split(".")[0]} else None`;
  if (field.type === "float") code = `float(${code}) if ${code.split(".")[0]} else None`;

  return code;
}

function genCustomSettings(d: SpiderDirective): string[] {
  const rate = d.rateLimit ?? PRESETS.standard;
  const lines: string[] = [
    `custom_settings = {`,
    `    "DOWNLOAD_DELAY": ${rate.downloadDelay},`,
    `    "CONCURRENT_REQUESTS": ${rate.concurrentRequests},`,
    `    "CONCURRENT_REQUESTS_PER_DOMAIN": ${rate.concurrentRequestsPerDomain},`,
    `    "RANDOMIZE_DOWNLOAD_DELAY": ${rate.randomizeDelay ? "True" : "False"},`,
  ];

  if (rate.autoThrottle) {
    lines.push(
      `    "AUTOTHROTTLE_ENABLED": True,`,
      `    "AUTOTHROTTLE_TARGET_CONCURRENCY": ${rate.autoThrottleTargetConcurrency},`,
      `    "AUTOTHROTTLE_MAX_DELAY": ${rate.autoThrottleMaxDelay},`,
    );
  }

  if (d.timeout !== 30) lines.push(`    "DOWNLOAD_TIMEOUT": ${d.timeout},`);
  if (d.retryTimes !== 3) lines.push(`    "RETRY_TIMES": ${d.retryTimes},`);
  if (d.depth > 0) lines.push(`    "DEPTH_LIMIT": ${d.depth},`);
  if (d.maxItems > 0) lines.push(`    "CLOSESPIDER_ITEMCOUNT": ${d.maxItems},`);

  if (d.output) {
    lines.push(`    "FEEDS": {"${d.output.path}": {"format": "${d.output.format}", "overwrite": ${d.output.overwrite ? "True" : "False"}}},`);
  }

  if (d.middlewares) {
    lines.push(`    "DOWNLOADER_MIDDLEWARES": ${JSON.stringify(d.middlewares).replace(/null/g, "None")},`);
  }
  if (d.pipelines) {
    lines.push(`    "ITEM_PIPELINES": ${JSON.stringify(d.pipelines).replace(/null/g, "None")},`);
  }

  for (const [k, v] of Object.entries(d.settings ?? {})) {
    lines.push(`    "${k}": ${JSON.stringify(v)},`);
  }

  lines.push(`}`);
  return lines;
}

export function generateSpider(d: SpiderDirective): string {
  const className = toPythonClassName(d.name);
  const base = BASE_CLASSES[d.type] ?? "Spider";
  const imports: string[] = [`import scrapy`];

  if (d.type === "crawl") {
    imports.push(
      `from scrapy.spiders import CrawlSpider, Rule`,
      `from scrapy.linkextractors import LinkExtractor`,
    );
  } else if (d.type === "sitemap") {
    imports.push(`from scrapy.spiders import SitemapSpider`);
  } else if (d.type === "feed") {
    imports.push(`from scrapy.spiders import XMLFeedSpider`);
  }

  const lines: string[] = [
    `"""${d.description}`,
    ``,
    `Generated by @jadecli/scrapy-cli from SpiderDirective.`,
    `Tags: ${d.tags.join(", ") || "none"}`,
    `"""`,
    ``,
    ...imports,
    ``,
    ``,
    `class ${className}(${d.type === "crawl" ? "CrawlSpider" : base}):`,
    `    name = "${d.name}"`,
    `    allowed_domains = ${JSON.stringify(d.allowedDomains)}`,
    `    start_urls = ${JSON.stringify(d.startUrls)}`,
    ``,
  ];

  // Custom settings
  lines.push(indent(genCustomSettings(d)));
  lines.push(``);

  // Auth
  if (d.auth) {
    if (d.auth.httpUser) lines.push(`    http_user = "${d.auth.httpUser}"`);
    if (d.auth.httpPass) lines.push(`    http_pass = "${d.auth.httpPass}"`);
    if (d.auth.headers) {
      lines.push(`    custom_headers = ${JSON.stringify(d.auth.headers, null, 8)}`);
    }
  }

  // CrawlSpider rules
  if (d.type === "crawl" && d.rules?.length) {
    lines.push(`    rules = (`);
    for (const rule of d.rules) {
      const deny = rule.deny ? `, deny=r"${rule.deny}"` : "";
      lines.push(`        Rule(LinkExtractor(allow=r"${rule.allow}"${deny}), callback="${rule.callback}", follow=${rule.follow ? "True" : "False"}),`);
    }
    lines.push(`    )`);
    lines.push(``);
  }

  // Parse method
  const parseMethod = d.type === "crawl" ? "parse_item" : "parse";
  lines.push(`    def ${parseMethod}(self, response):`);

  // Yield item
  lines.push(`        yield {`);
  for (const field of d.fields) {
    const code = genSelectorCode(field);
    lines.push(`            "${field.name}": ${code},`);
  }
  lines.push(`            "url": response.url,`);
  lines.push(`            "crawled_at": scrapy.utils.misc.load_object("datetime.datetime").now().isoformat(),`);
  lines.push(`        }`);

  // Pagination for API spiders
  if (d.pagination) {
    lines.push(``);
    lines.push(`        # Pagination`);
    lines.push(`        next_page = response.css("${d.pagination.nextPage}").get()`);
    lines.push(`        if next_page:`);
    lines.push(`            yield response.follow(next_page, callback=self.${parseMethod})`);
  }

  return lines.join("\n") + "\n";
}
